### ISSUE TITLE
 Deprecation: posts.[] should be changed to posts.docs.[].

### ISSUE THREAD

**Issue by unixfreaxjp** [Sodaware/jekyll-archive-page#1]
When I applied the plugin, it shows error during `bundle exec jekyll serve` with the detail as followings:
````asm
      Generating...
       Deprecation: posts.[] should be changed to posts.docs.[].
                    Called by /SOURCEDIR/_plugins/archive_page.rb:49:in `get_grouped_posts'.
jekyll 3.1.6 | Error:  undefined method `year' for #<Jekyll::Document:0x2a182ef8>
````
Deprecation is pointing to the codes in this function:
````ruby
    def get_grouped_posts
      
      # Get date of first post
start_year = site.posts[0].year
                          ^^^^^^^^
````
version:
````bash
$ jekyll --version
jekyll 3.1.6
````
Please kindly look it up? 

Reference: 
http://stackoverflow.com/questions/24179283/get-jekyll-posts-by-year
http://stackoverflow.com/questions/19086284/jekyll-liquid-templating-how-to-group-blog-posts-by-year

**Comment by Sodaware** [comment]
Thank you for the detailed bug report - this is now fixed.

**Comment by unixfreaxjp** [comment]
Thank you!
